"""Modify useragenda

Revision ID: 2cda93b66673
Revises: 58f09616def9
Create Date: 2023-02-11 17:03:40.557739

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2cda93b66673'
down_revision = '58f09616def9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agenda', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start_time', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('repeat_interval', sa.Interval(), nullable=True))
        batch_op.drop_column('date_time')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('user_type',
               existing_type=postgresql.ENUM('PATIENT', 'CAREGIVER', name='eusertype'),
               type_=sa.String(length=20),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('user_type',
               existing_type=sa.String(length=20),
               type_=postgresql.ENUM('PATIENT', 'CAREGIVER', name='eusertype'),
               existing_nullable=False)

    with op.batch_alter_table('agenda', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
        batch_op.drop_column('repeat_interval')
        batch_op.drop_column('start_time')

    # ### end Alembic commands ###
