"""remove faces

Revision ID: 67a7d47cc1ff
Revises: dd7424f2e9cf
Create Date: 2023-02-20 15:21:32.329925

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67a7d47cc1ff'
down_revision = 'dd7424f2e9cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # op.drop_table('spatial_ref_sys')
    with op.batch_alter_table('userfaces', schema=None) as batch_op:
        batch_op.add_column(sa.Column('face_url', sa.String(length=100), nullable=True))
        batch_op.drop_constraint('userfaces_face_id_fkey', type_='foreignkey')
        batch_op.drop_column('face_id')
    op.drop_table('faces')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('userfaces', schema=None) as batch_op:
        batch_op.add_column(sa.Column('face_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('userfaces_face_id_fkey', 'faces', ['face_id'], ['id'])
        batch_op.drop_column('face_url')

    # op.create_table('spatial_ref_sys',
    # sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    # sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    # sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    # sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    # sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    # sa.CheckConstraint('srid > 0 AND srid <= 998999', name='spatial_ref_sys_srid_check'),
    # sa.PrimaryKeyConstraint('srid', name='spatial_ref_sys_pkey')
    # )
    op.create_table('faces',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('type', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='faces_pkey')
    )
    # ### end Alembic commands ###
